sudo: false
language: node_js
node_js:
- '5'
notifications:
  webhooks:
    on_success: change
    on_failure: always
script:
- bash ./scripts/deploy-to-gh-pages.sh
env:
  global:
  - GITHUB_REPO: o-v/gh-pages-spike
# travis-encrypt -r o-v/gh-pages-spike -k GH_TOKEN blahblahblah  
  - secure: tPzuIhRoDCXe8rSEgekkOa3XBsklcfY7VNi9aQbnOhhAwSz+IcQ2W8KXtXFXwf6nENI74uqodunM/+v+OOpCNUOCgUIrZ7Sl5qaiM6D3wxBV3hboV7rmFQ2gg6wTd8raimLEd8bBqP3YcBmuTeTaTEQaFhKqYwRFct57OecoxWA3P6KU3QNlLPEk1+dftFHxtZ2ka30qLpX5s7S84pVdqKoayayJuKTUAs5GzIu2yPGITeoYuEoWs4IS6Jj/D8YT5QrqUGcjVJyI2mrZwpESuIj0cGO8T8ZMUz2IfZ8zQY6iuFSLm5TEYcuRj5KiZ0d4B9oP1a18H15LeCldH3wn6P7k6m5+gdarDHSFken9902iU5rogEoVQACoasQxVjxySp+toHr+lllMOPJNXK4gBzZMkrhkak3+/L1V1wA/We7R7GSlkICisFOs9/1OxG8pl1S0byY/jiT7RtFSJ0jItdUl4+RK/cM1jn1i8LfG16AiJ90NZkhMEAh51UXqujqatuTUkDJHokE4PeimmQ80fy6m40ezmrshtAwyf39foisQq8+gVv3A6iXXtvu0ipEQ6u4OjK0Qy/q0zpOcenWMR7bAg2vhuuQCQVYwlQDwqV8wlYPSTFURuk/mYdv4QCWNR+PCTI++5WIKeXtFjEinEJ+Hh0Lyy8YaTFq965gtkHw=
cache:
  directories:
    - node_modules